#
#   This is the core configuration for a configuration service.  I have two examples here:
#
#       -  A configuration service which completelty loads the configuration for the services
#          from the local file server of the config service.  This should only be used for
#          demonstration purposes or for a small application with a limited number of services.
#
#       -  A configuraton service that uses a git-based repository to read the files from
#
####################################
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/anthonydenecheau/config-repo
          searchPaths: zuulservice, onlinedogshowservice, sub-onlinedogshow-daemon, pub-onlinedogshow-daemon, dogservice, subdogdaemon, pubdogdaemon, judgeservice, showservice, lofselectclubservice
          username: anthonydenecheau
          password: "{cipher}39929a669a72a5943055a852c45e1fe4272942aa34f4d64f5be383f93d7c5da8"
